In [1]:
import pandas as pd

In [2]:
url_data = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')

In [13]:
url_data

[        Rk             Player   Age Team  Pos     G    GS      MP     FG  \
 0      1.0       James Harden  25.0  HOU   SG  81.0  81.0  2981.0  647.0
 1      2.0      Stephen Curry  26.0  GSW   PG  80.0  80.0  2613.0  653.0
 2      3.0  Russell Westbrook  26.0  OKC   PG  67.0  67.0  2302.0  627.0
 3      4.0       LeBron James  30.0  CLE   SF  69.0  69.0  2493.0  624.0
 4      5.0     Damian Lillard  24.0  POR   PG  82.0  82.0  2925.0  590.0
 ..     ...                ...   ...  ...  ...   ...   ...     ...    ...
 647  489.0        Malcolm Lee  24.0  PHI   SG   1.0   0.0     2.0    0.0
 648  490.0        Kalin Lucas  25.0  MEM   PG   1.0   0.0     6.0    0.0
 649  491.0       Ronny Turiaf  32.0  MIN    C   2.0   0.0    19.0    0.0
 650  492.0         David Wear  24.0  SAC   PF   2.0   0.0     7.0    0.0
 651    NaN     League Average   NaN  NaN  NaN   NaN   NaN     NaN    NaN

         FGA  ...    DRB    TRB    AST    STL   BLK    TOV     PF     PTS  \
 0    1470.0  ...  384.0  459.0  565.0  154.0  60.0  321.0  208.0  2217.0
 1    1341.0  ...  285.0  341.0  619.0  163.0  16.0  249.0  158.0  1900.0
 2    1471.0  ...  364.0  488.0  574.0  140.0  14.0  293.0  184.0  1886.0
 3    1279.0  ...  365.0  416.0  511.0  109.0  49.0  272.0  135.0  1743.0
 4    1360.0  ...  329.0  378.0  507.0   97.0  21.0  222.0  164.0  1720.0
 ..      ...  ...    ...    ...    ...    ...   ...    ...    ...     ...
 647     1.0  ...    0.0    0.0    0.0    0.0   0.0    0.0    0.0     0.0
 648     1.0  ...    0.0    0.0    0.0    1.0   0.0    0.0    1.0     0.0
 649     0.0  ...    1.0    1.0    2.0    0.0   0.0    0.0    0.0     0.0
 650     2.0  ...    0.0    2.0    1.0    0.0   0.0    0.0    1.0     0.0
 651     NaN  ...    NaN    NaN    NaN    NaN   NaN    NaN    NaN     NaN

      Trp-Dbl                 Awards
 0        4.0          MVP-2,AS,NBA1
 1        0.0          MVP-1,AS,NBA1
 2       11.0          MVP-4,AS,NBA2
 3        2.0  MVP-3,DPOY-13,AS,NBA1
 4        0.0                     AS
 ..       ...                    ...
 647      0.0                    NaN
 648      0.0                    NaN
 649      0.0                    NaN
 650      0.0                    NaN
 651      NaN                    NaN

 [652 rows x 32 columns],
         Rk           Player   Age Team  Pos     G    GS     MP     FG    FGA  \
 0      1.0     LeBron James  30.0  CLE   SF  20.0  20.0  844.0  227.0  544.0
 1      2.0    Stephen Curry  26.0  GSW   PG  21.0  21.0  826.0  200.0  439.0
 2      3.0     James Harden  25.0  HOU   SG  17.0  17.0  636.0  129.0  294.0
 3      4.0    Klay Thompson  24.0  GSW   SG  21.0  21.0  761.0  149.0  334.0
 4      5.0    Blake Griffin  25.0  LAC   PF  14.0  14.0  557.0  140.0  274.0
 ..     ...              ...   ...  ...  ...   ...   ...    ...    ...    ...
 204  205.0       Greg Smith  24.0  DAL   PF   1.0   0.0    1.0    0.0    0.0
 205  206.0       Russ Smith  23.0  MEM   PG   2.0   0.0    3.0    0.0    0.0
 206  207.0  Mirza Teletović  29.0  BRK   PF   3.0   0.0   16.0    0.0    5.0
 207  208.0   Gerald Wallace  32.0  BOS   SF   1.0   0.0    4.0    0.0    1.0
 208    NaN   League Average   NaN  NaN  NaN   NaN   NaN    NaN    NaN    NaN

      ...    DRB    TRB    AST   STL   BLK   TOV    PF    PTS  Trp-Dbl  Awards
 0    ...  189.0  226.0  169.0  33.0  21.0  82.0  58.0  601.0      3.0     NaN
 1    ...   85.0  105.0  134.0  39.0   3.0  82.0  47.0  594.0      0.0     NaN
 2    ...   85.0   97.0  128.0  28.0   7.0  77.0  49.0  462.0      1.0     NaN
 3    ...   72.0   81.0   54.0  16.0  19.0  41.0  64.0  391.0      0.0     NaN
 4    ...  140.0  178.0   86.0  14.0  14.0  45.0  43.0  357.0      3.0     NaN
 ..   ...    ...    ...    ...   ...   ...   ...   ...    ...      ...     ...
 204  ...    0.0    0.0    0.0   0.0   0.0   0.0   0.0    0.0      0.0     NaN
 205  ...    0.0    0.0    2.0   0.0   0.0   0.0   0.0    0.0      0.0     NaN
 206  ...    4.0    4.0    0.0   1.0   0.0   1.0   1.0    0.0      0.0     NaN
 207  ...    1.0    1.0    0.0   0.0   0.0   0.0   0.0    0.0      0.0     NaN
 208  ...    NaN    NaN    NaN   NaN   NaN   NaN   NaN    NaN      NaN     NaN

 [209 rows x 32 columns]]

In [6]:
type(url_data)

list

In [7]:
len(url_data)

2

In [8]:
df1 = url_data[0]
df1.head()

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1.0,James Harden,25.0,HOU,SG,81.0,81.0,2981.0,647.0,1470.0,...,384.0,459.0,565.0,154.0,60.0,321.0,208.0,2217.0,4.0,"MVP-2,AS,NBA1"
1,2.0,Stephen Curry,26.0,GSW,PG,80.0,80.0,2613.0,653.0,1341.0,...,285.0,341.0,619.0,163.0,16.0,249.0,158.0,1900.0,0.0,"MVP-1,AS,NBA1"
2,3.0,Russell Westbrook,26.0,OKC,PG,67.0,67.0,2302.0,627.0,1471.0,...,364.0,488.0,574.0,140.0,14.0,293.0,184.0,1886.0,11.0,"MVP-4,AS,NBA2"
3,4.0,LeBron James,30.0,CLE,SF,69.0,69.0,2493.0,624.0,1279.0,...,365.0,416.0,511.0,109.0,49.0,272.0,135.0,1743.0,2.0,"MVP-3,DPOY-13,AS,NBA1"
4,5.0,Damian Lillard,24.0,POR,PG,82.0,82.0,2925.0,590.0,1360.0,...,329.0,378.0,507.0,97.0,21.0,222.0,164.0,1720.0,0.0,AS

In [10]:
df1.shape

(652, 32)

In [14]:
df2 = url_data[1]
df2.head()

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1.0,LeBron James,30.0,CLE,SF,20.0,20.0,844.0,227.0,544.0,...,189.0,226.0,169.0,33.0,21.0,82.0,58.0,601.0,3.0,NaN
1,2.0,Stephen Curry,26.0,GSW,PG,21.0,21.0,826.0,200.0,439.0,...,85.0,105.0,134.0,39.0,3.0,82.0,47.0,594.0,0.0,NaN
2,3.0,James Harden,25.0,HOU,SG,17.0,17.0,636.0,129.0,294.0,...,85.0,97.0,128.0,28.0,7.0,77.0,49.0,462.0,1.0,NaN
3,4.0,Klay Thompson,24.0,GSW,SG,21.0,21.0,761.0,149.0,334.0,...,72.0,81.0,54.0,16.0,19.0,41.0,64.0,391.0,0.0,NaN
4,5.0,Blake Griffin,25.0,LAC,PF,14.0,14.0,557.0,140.0,274.0,...,140.0,178.0,86.0,14.0,14.0,45.0,43.0,357.0,3.0,NaN

In [15]:
df2.shape

(209, 32)

In [16]:
df1.columns

Index(['Rk', 'Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Trp-Dbl', 'Awards'],
      dtype='object')

In [17]:
df2.columns

Index(['Rk', 'Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Trp-Dbl', 'Awards'],
      dtype='object')

In [18]:
df1[['Rk','Player','Team','Awards']]

        Rk             Player Team                 Awards
0      1.0       James Harden  HOU          MVP-2,AS,NBA1
1      2.0      Stephen Curry  GSW          MVP-1,AS,NBA1
2      3.0  Russell Westbrook  OKC          MVP-4,AS,NBA2
3      4.0       LeBron James  CLE  MVP-3,DPOY-13,AS,NBA1
4      5.0     Damian Lillard  POR                     AS
..     ...                ...  ...                    ...
647  489.0        Malcolm Lee  PHI                    NaN
648  490.0        Kalin Lucas  MEM                    NaN
649  491.0       Ronny Turiaf  MIN                    NaN
650  492.0         David Wear  SAC                    NaN
651    NaN     League Average  NaN                    NaN

[652 rows x 4 columns]

In [19]:
df2[['Rk','Player','Team','Awards']]

        Rk           Player Team Awards
0      1.0     LeBron James  CLE    NaN
1      2.0    Stephen Curry  GSW    NaN
2      3.0     James Harden  HOU    NaN
3      4.0    Klay Thompson  GSW    NaN
4      5.0    Blake Griffin  LAC    NaN
..     ...              ...  ...    ...
204  205.0       Greg Smith  DAL    NaN
205  206.0       Russ Smith  MEM    NaN
206  207.0  Mirza Teletović  BRK    NaN
207  208.0   Gerald Wallace  BOS    NaN
208    NaN   League Average  NaN    NaN

[209 rows x 4 columns]

In [ ]:
df1.to_excel('regular_season.xlsx', index=False)

In [21]:
df2.to_csv('playoff.csv', index=False)